name: AQI CI CD Pipeline

on:
  schedule:
    - cron: '5 * * * *'      # feature pipeline run hourly 
    - cron: '0 19 * * *'      # training pipeline run at 12:00 AM PKT 
  workflow_dispatch:

jobs:

  # ---------------- FEATURE PIPELINE (HOURLY) ----------------
  feature-pipeline:
    if: github.event.schedule == '5 * * * *'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Feature Pipeline
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: |
        python pipelines/feature_pipeline.py


  # ---------------- TRAINING PIPELINE (DAILY) ----------------
  training-pipeline:
    if: github.event.schedule == '0 19 * * *'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Training Pipeline
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: |
        python pipelines/training_pipeline.py